# Generated by Django 4.1.7 on 2023-04-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("tax_ID", models.IntegerField(default=0)),
                ("email_address", models.CharField(max_length=150)),
                ("home_address", models.TextField()),
                ("password", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="OrderedProduct",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                ("description", models.TextField()),
                ("price", models.FloatField(default=0)),
                ("warranty_status", models.CharField(max_length=100)),
                ("distributor_info", models.TextField()),
                ("order_number", models.CharField(max_length=100)),
                ("delivery_address", models.TextField()),
                (
                    "order_process_status",
                    models.CharField(default="processing", max_length=100),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Product.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InStockProduct",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="Product/static/img/")),
                ("name", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                ("description", models.TextField()),
                ("quantity_in_stocks", models.IntegerField()),
                ("price", models.FloatField(default=0)),
                ("warranty_status", models.CharField(max_length=100)),
                ("distributor_info", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        default="Toy",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="Product.category",
                    ),
                ),
            ],
        ),
    ]
