# Generated by Django 4.2.1 on 2023-05-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_alter_orderedproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='instockproduct',
            name='popularity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
