# Generated by Django 4.1.7 on 2023-06-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_purchasedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instockproduct',
            name='newPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='instockproduct',
            name='purchased_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='purchased_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasedproduct',
            name='purchased_price',
            field=models.FloatField(default=0),
        ),
    ]
