# Generated by Django 4.2.1 on 2023-06-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_purchasedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='instockproduct',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
