# Generated by Django 4.1.7 on 2023-03-31 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InStockProduct',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/img/')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
                ('quantity_in_stocks', models.IntegerField()),
                ('price', models.FloatField(default=0)),
                ('warranty_status', models.CharField(max_length=100)),
                ('distributor_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tax_ID', models.IntegerField(default=0)),
                ('email_address', models.CharField(max_length=150)),
                ('home_address', models.TextField()),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('warranty_status', models.CharField(max_length=100)),
                ('distributor_info', models.TextField()),
                ('order_number', models.CharField(max_length=100)),
                ('delivery_address', models.TextField()),
                ('order_process_status', models.CharField(default='processing', max_length=100)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.user')),
            ],
        ),
    ]
